"""initial_tenant_schema

Revision ID: d2ebbb76fc6f
Revises: 
Create Date: 2026-03-06 09:54:17.551165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'd2ebbb76fc6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('scan_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('library_id')
    )
    op.create_table('people',
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('system_metadata',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('rel_path', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proxy_key', sa.String(), nullable=True),
    sa.Column('thumbnail_key', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.library_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('library_id', 'rel_path', name='uq_assets_library_rel_path')
    )
    op.create_table('asset_metadata',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('exif_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sharpness_score', sa.Float(), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('ai_description', sa.String(), nullable=True),
    sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_ocr_text', sa.String(), nullable=True),
    sa.Column('ai_description_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding_vector', Vector(512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('faces',
    sa.Column('face_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('bounding_box_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_vector', Vector(512), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('face_id')
    )
    op.create_table('video_scenes',
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('rep_frame_ms', sa.Integer(), nullable=False),
    sa.Column('proxy_key', sa.String(), nullable=True),
    sa.Column('thumbnail_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('scene_id')
    )
    op.create_table('face_person_matches',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('face_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['face_id'], ['faces.face_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.person_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('search_sync_queue',
    sa.Column('sync_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['video_scenes.scene_id'], ),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_table('worker_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('scene_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['video_scenes.scene_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_jobs')
    op.drop_table('search_sync_queue')
    op.drop_table('face_person_matches')
    op.drop_table('video_scenes')
    op.drop_table('faces')
    op.drop_table('asset_metadata')
    op.drop_table('assets')
    op.drop_table('system_metadata')
    op.drop_table('people')
    op.drop_table('libraries')
    # ### end Alembic commands ###
