import Foundation

/// Persistent disk cache for proxy images, compatible with the Python CLI's proxy cache.
///
/// Both clients share `~/.cache/lumiverb/proxies/` so proxies generated by
/// either client are reusable. See `docs/proxy-cache-protocol.md`.
///
/// File layout per asset:
/// - `{asset_id}` — JPEG proxy bytes (2048px max long edge)
/// - `{asset_id}.sha` — SHA-256 hex string of the source file
public final class ProxyCacheOnDisk: @unchecked Sendable {
    public static let shared = ProxyCacheOnDisk()

    private let cacheDir: URL

    public init(cacheDir: URL? = nil) {
        if let cacheDir {
            self.cacheDir = cacheDir
        } else {
            self.cacheDir = FileManager.default.homeDirectoryForCurrentUser
                .appendingPathComponent(".cache/lumiverb/proxies")
        }
        try? FileManager.default.createDirectory(
            at: self.cacheDir,
            withIntermediateDirectories: true
        )
    }

    // MARK: - Scan operations

    /// Store a proxy image and SHA sidecar from scan.
    /// Writes are atomic (temp + rename) so concurrent readers never see partial files.
    public func putScan(assetId: String, jpegData: Data, sourceSHA256: String) {
        atomicWrite(data: jpegData, to: proxyURL(assetId))
        atomicWrite(data: Data(sourceSHA256.utf8), to: shaURL(assetId))
    }

    /// Read the SHA-256 sidecar for an asset. Returns nil if missing.
    public func getSHA(assetId: String) -> String? {
        let url = shaURL(assetId)
        guard let data = try? Data(contentsOf: url),
              let sha = String(data: data, encoding: .utf8) else {
            return nil
        }
        return sha.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Check if a proxy needs regeneration by comparing source SHA.
    /// Returns `true` if the cached proxy is valid and can be reused.
    public func isValid(assetId: String, sourceSHA256: String) -> Bool {
        guard let cachedSHA = getSHA(assetId: assetId) else { return false }
        guard cachedSHA == sourceSHA256 else { return false }
        // Also verify the proxy file exists (sidecar without proxy = incomplete)
        return FileManager.default.fileExists(atPath: proxyURL(assetId).path)
    }

    // MARK: - Browse operations

    /// Get cached proxy bytes for display. Returns nil if not cached.
    public func get(assetId: String) -> Data? {
        let url = proxyURL(assetId)
        return try? Data(contentsOf: url)
    }

    /// Cache proxy bytes downloaded from the server for future display.
    public func put(assetId: String, data: Data) {
        atomicWrite(data: data, to: proxyURL(assetId))
    }

    /// Check if a proxy exists in the cache.
    public func has(assetId: String) -> Bool {
        FileManager.default.fileExists(atPath: proxyURL(assetId).path)
    }

    // MARK: - Maintenance

    /// Remove a single entry and its SHA sidecar.
    public func remove(assetId: String) {
        try? FileManager.default.removeItem(at: proxyURL(assetId))
        try? FileManager.default.removeItem(at: shaURL(assetId))
    }

    // MARK: - Paths

    private func proxyURL(_ assetId: String) -> URL {
        cacheDir.appendingPathComponent(assetId)
    }

    private func shaURL(_ assetId: String) -> URL {
        cacheDir.appendingPathComponent("\(assetId).sha")
    }

    // MARK: - Atomic write

    private func atomicWrite(data: Data, to destination: URL) {
        let tempURL = cacheDir.appendingPathComponent(UUID().uuidString + ".tmp")
        do {
            try data.write(to: tempURL, options: .atomic)
            // .atomic already writes to temp + renames, but we do our own
            // to match the Python protocol exactly
            if FileManager.default.fileExists(atPath: destination.path) {
                try FileManager.default.removeItem(at: destination)
            }
            try FileManager.default.moveItem(at: tempURL, to: destination)
        } catch {
            try? FileManager.default.removeItem(at: tempURL)
        }
    }
}
